### PR TITLE
WASM binding

### PR DESCRIPTION
**Pull request by anakrish**

### CODE REVIEW

**Comment by anakrish** [comment]
@unexge Can you review this PR? I'm thinking of housing all the bindings under `src/bindings`

**Comment by anakrish** [comment]
Merging to make progress.

**Comment by unexge** [comment]
Hey @anakrish, sorry I was on vacation. The changes look good to me. Yes, we can put all bindings as separate crates in `bindings/`, that makes sense!

**Comment by anakrish** [comment]
> sorry I was on vacation

No worries. I'm trying to close out many things before Jan end.

**Pull request merged**
