### PR TITLE
Revert "chore: release v0.2.0"

### PR DESCRIPTION
**Pull request by anakrish**
Reverts microsoft/regorus#257

### CODE REVIEW

**Comment by jdgo-mars** [comment]
Hi, first of all thank you for the work you do!

**Comment by jdgo-mars** [comment]
Hi, first of all thank you for the work you do
since there is no context here

**Comment by jdgo-mars** [comment]
Hi, first for all thank you for the work you do!
Regarding `0.2.0` release: after this revert, bindings are not in sync with current version.
Is there a specific reason for this?
Thank you!

**Comment by anakrish** [comment]
@jdgo-mars, Thanks for reporting it. There is no special reason for it. At the time, that was the quickest way for me to get to a stage to publish v0.2.0.

I will manually fix the version numbers of extensions for now.
Going forward we need some way to update the version numbers consistently even though we only publish the main regorus crate.

**Pull request merged**
