### PR TITLE
Add tests for builtin strings::indexof method

### LINKED ISSUE #12: [Testing] Add test cases for strings builtins
String bultins are defined in https://github.com/microsoft/regorus/blob/main/src/builtins/strings.rs.

Tests need to be written similar to tests for arrays builtins: https://github.com/microsoft/regorus/tree/main/tests/interpreter/cases/builtins/arrays

### PR DESCRIPTION
**Pull request by Sumynwa**
Partly fixes #12

### CODE REVIEW

**Comment by anakrish** [comment]
@Sumynwa Thanks for the contribution.

There is a failure unrelated to your change, when building the Java binding. It would be great if you can fix that too:

```
error: match can be simplified with `.unwrap_or_default()`
  --> src/utils.rs:81:5
   |
81 | /     match get_extra_arg_impl(expr, module, functions) {
82 | |         Ok(a) => a,
83 | |         _ => None,
84 | |     }
   | |_____^ help: replace it with: `get_extra_arg_impl(expr, module, functions).unwrap_or_default()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#manual_unwrap_or_default
   = note: `-D clippy::manual-unwrap-or-default` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::manual_unwrap_or_default)]`

error: could not compile `regorus` (lib) due to 1 previous error
```

**Comment by Sumynwa** [comment]
@anakrish Yes, I will fix the clippy lint error.

**Comment by anakrish** [comment]
@Sumynwa I have fixed the clippy lint error as part of another PR. Can you rebase to latest main and push?

**Review by anakrish — APPROVED** [review]
LGTM

**Review by anakrish — APPROVED** [review]
LGTM

**Pull request merged**
